### ISSUE TITLE
您好，请您分享一份驱动

### ISSUE THREAD

**Issue by unlockbl-sh** [Zero-zer0/Miix700-OSX-Hackintosh-Clover#1]
您好，我和您是同一款机器，也按照您的意见安装了DW1820a的卡，请您分享一下Mac里的WiFi和蓝牙的驱动，可以吗？

**Comment by Zero-zer0** [comment]
值得注意的是，只有部分版本的DW1820A能在MIIX 700上正常驱动
WiFi部分理论免驱，除了一个[AirportBrcmFixup](https://github.com/acidanthera/AirportBrcmFixup)用来解决5Ghz与“第三方卡”的问题以外，不需要修改任何系统目录中的文件，比如IO80211Family.kext；也不需要通过Clover注入设备属性

如果你的DW1820A的WIFI没有做到OOB（即插即用），正确的姿势应该是换一个版本的DW1820A
经过我的测试，能成功驱动上WIFI的有（BTW这让我的触摸屏直接裂了）：
1.   `096JNT`, ID为`1028:0022`，背面为`BCM94350ZAE`，没有屏蔽任何针脚，即插即用，不影响休眠
2.   `08PKF4`, ID为`1020:0023`, 背面为`BCM94356ZEPA50DX`,但是休眠唤醒后会导致Freeze
其他的比如`0VW3T3`的`BCM94356ZEPA50DX`,联想版`00JT493`都无法驱动

蓝牙方面，我使用的是[BrcmPatchRam](https://github.com/acidanthera/BrcmPatchRAM)
在使用前请阅读文档，在C/L/O目录下使用`BrcmPatchRAM3.kext`+`BrcmFirmwareData.kext`+`
BrcmBluetoothInjector.kext`，在系统信息——蓝牙部分看到固件版本为`v4689`代表固件上传成功。

希望能够对你有所帮助。
